#!/bin/bash

set -ex

REPO="mainline"

if [ $# -ne 1 ]; then
	echo "Please provide a repository to update the testing instance!"
	echo "The supported repositories are as follows:"
	echo "  - mainline"
	echo "  - linux-next"
	echo "  - openeuler"
	exit 0
fi

case $1 in
	mainline*)
		REPO="mainline"
		;;
	linux-next*)
		REPO="linux-next"
		;;
	openeuler*)
		REPO="openeuler"
		;;
	*)
		echo "No such kernel repository"
		exit -1
esac

echo $kernel

# update the smatch repository
pushd smatch
git pull
popd

# update the testing kernel and run smatch
pushd ${REPO}
./deploy_smatch_on_*.sh
popd
